# ============================================================================
# Stage 1: Composer Dependencies
# ============================================================================
FROM composer:2 AS deps

WORKDIR /app

COPY composer.json composer.lock ./
# The composer:2 image lacks pcntl, posix and intl; the FrankenPHP runtime image
# provides all three, and stage 3 asserts that before the build is allowed to finish.
RUN composer install --no-dev --no-scripts --no-autoloader --prefer-dist --no-interaction \
    --ignore-platform-req=ext-pcntl \
    --ignore-platform-req=ext-posix \
    --ignore-platform-req=ext-intl

COPY . .
RUN composer dump-autoload --optimize --no-dev
RUN php artisan wayfinder:generate --with-form 2>/dev/null || true

# ============================================================================
# Stage 2: Frontend Assets
# ============================================================================
FROM node:22-alpine AS frontend

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

COPY vite.config.ts tsconfig.json ./
COPY resources ./resources
COPY public ./public

# Overwrite Wayfinder types with freshly generated ones from deps stage
COPY --from=deps /app/resources/js/actions ./resources/js/actions
COPY --from=deps /app/resources/js/routes ./resources/js/routes
# Copy Wayfinder runtime helper directory (gitignored, generated by wayfinder:generate)
COPY --from=deps /app/resources/js/wayfinder ./resources/js/wayfinder

# Wayfinder Vite plugin shim
RUN printf '#!/bin/sh\nexit 0\n' > /usr/local/bin/php && chmod +x /usr/local/bin/php

RUN NODE_OPTIONS=--dns-result-order=ipv4first npm run build

# ============================================================================
# Stage 3: Production Runtime (Using Base Image)
# ============================================================================
FROM nexudev/laravel-octane-frankenphp:base AS production

WORKDIR /app

# Performance Tuning — Configurable Workers
# Default to "auto" (CPU cores). To scale up, pass e.g. -e OCTANE_WORKERS=256 at runtime.
ENV OCTANE_WORKERS=auto

# Standard Production Env
ENV APP_ENV=production \
    APP_DEBUG=false \
    OCTANE_SERVER=frankenphp \
    LOG_CHANNEL=stderr \
    LOG_LEVEL=info

# Optimized PHP Configuration
RUN { \
    echo 'opcache.enable=1'; \
    echo 'opcache.enable_cli=1'; \
    echo 'opcache.memory_consumption=512'; \
    echo 'opcache.interned_strings_buffer=64'; \
    echo 'opcache.max_accelerated_files=32531'; \
    echo 'opcache.validate_timestamps=0'; \
    echo 'opcache.jit=tracing'; \
    echo 'opcache.jit_buffer_size=128M'; \
    echo 'realpath_cache_size=4096K'; \
    echo 'realpath_cache_ttl=600'; \
    } > /usr/local/etc/php/conf.d/performance.ini

# The dependency stage had to ignore three platform requirements its own image
# does not satisfy. Assert the runtime really provides them, so a base image that
# drops one fails the build here instead of 500ing on a request.
RUN for ext in pcntl posix intl; do \
    php -r "exit(extension_loaded('$ext') ? 0 : 1);" \
    || { echo "Runtime image is missing required PHP extension: $ext" >&2; exit 1; }; \
    done

# Copy Composer dependencies from deps stage
COPY --from=deps /app/vendor ./vendor

# Copy compiled frontend assets from frontend stage
COPY --from=frontend /app/public/build ./public/build
COPY --from=frontend /app/resources/js/wayfinder ./resources/js/wayfinder

# Copy application source code
COPY . .

# Final cleanup and optimization
RUN php artisan horizon:publish --no-interaction && \
    php artisan config:cache && \
    php artisan route:cache && \
    php artisan view:cache

# ─── Permissions ──────────────────────────────────────────────────────
RUN mkdir -p \
    storage/logs \
    storage/framework/cache/data \
    storage/framework/sessions \
    storage/framework/views \
    bootstrap/cache \
    && chown -R www-data:www-data \
    storage \
    bootstrap/cache \
    && chmod -R 775 \
    storage \
    bootstrap/cache

# ─── Supervisor configuration ────────────────────────────────────────
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# ─── Entrypoint ──────────────────────────────────────────────────────
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
    CMD curl -fsS -o /dev/null -w "%{http_code}" http://localhost:8000/up | grep -q "^200$" || exit 1

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"] 